#!/bin/bash
#
# brightness-ctl
#   Helper script for brightness control

### Volume control commands ###
if [[ $1 = 'increase' ]]; then
    brightnessctl -q set 5%+
elif [[ $1 = 'decrease' ]]; then
    brightnessctl -q set 5%-
fi

### Volume display notification ###
ICON="/usr/share/icons/Papirus-Dark/16x16/actions/brightnesssettings.svg"

BAR="┃"
PROGRESS_BGT=$(brightnessctl i | awk '/Current/ {print $4}' | sed 's/[()%]//g')
PROGRESS_BAR=$(for i in `seq 1 $(( PROGRESS_BGT / 5))`; do echo -n "$BAR"; done)
PROGRESS_PAD=$(for i in `seq 0 $(( 19 - PROGRESS_BGT / 5))`; do echo -ne '─'; done)

printf -v PROGRESS_TXT -- "%s%s [%4s]" "$PROGRESS_BAR" "$PROGRESS_PAD" "$PROGRESS_BGT%"

dunstify -a "brightness-ctl" -u low -I "$ICON" -h string:x-dunst-stack-tag:brightnessctl "" "$PROGRESS_TXT"
