#!/bin/bash
#
# vpntoggle-ctl
#  A simple script for connecting/disconnecting the VPN

if [[ "$(nordvpn status | grep 'Connected')" ]] then 
    nordvpn d 
    nordvpn set killswitch off

else
    nordvpn c
    nordvpn set killswitch on

fi
