#!/bin/bash
# ------------------------------------------------------------------------------
# dwminho-st-battery  (c) Copyright 2025-  Minho <minhotmog@gmail.com>
#  Battery module for the dwminho-blocks status bar
# ------------------------------------------------------------------------------

#  VARIABLES AND PREPROCESSING -------------------------------------------------
BAT_STATS=$(cat /sys/class/power_supply/BAT?/status)
BAT_LEVEL=$(cat /sys/class/power_supply/BAT?/capacity)

RUN_FOLDR=/run/user/$UID/dwminho-sb      # Temporary folder for the .lock files
mkdir -p $RUN_FOLDR                      # Creates the folder if does not exist

#  BATTERY HOT-PLUGGING --------------------------------------------------------
if [[ $1 == "plug" ]]; then 
    dunstify -C 0667
    touch $RUN_FOLDR/battery05notify.lock
    touch $RUN_FOLDR/battery10notify.lock
    touch $RUN_FOLDR/battery20notify.lock
    aplay /usr/share/sounds/dwminho/fx_connect.wav

elif [[ $1 == "unplug" ]]; then
    rm -f $RUN_FOLDR/*
    aplay /usr/share/sounds/dwminho/fx_disconnect.wav

fi

#  BATTERY NOTIFICATIONS -------------------------------------------------------
ICON_PATH="/usr/share/icons/Papirus-Dark/16x16/panel"

if [[ $BAT_LEVEL -le 5 && ! -f "$RUN_FOLDR/battery05notify.lock" ]]; then
    touch $RUN_FOLDR/battery05notify.lock
    touch $RUN_FOLDR/battery10notify.lock
    touch $RUN_FOLDR/battery20notify.lock
    systemctl suspend   # Safety suspend to avoid battery full discharge

elif [[ $BAT_LEVEL -le 10 && ! -f "$RUN_FOLDR/battery10notify.lock" ]]; then
    touch $RUN_FOLDR/battery10notify.lock
    touch $RUN_FOLDR/battery20notify.lock
    aplay /usr/share/sounds/dwminho/fx_notify_normal.wav

    dunstify -r 0667 -u critical -I "$ICON_PATH/battery-010.svg" \
        -h string:x-dunst-stack-tag:batterynotify "WARNING" "Battery below 10%"

elif [[ $BAT_LEVEL -le 20 && ! -f "$RUN_FOLDR/battery20notify.lock" ]]; then
    touch $RUN_FOLDR/battery20notify.lock
    aplay /usr/share/sounds/dwminho/fx_notify_normal.wav

    dunstify -r 0667 -u normal -I "$ICON_PATH/battery-020.svg" \
        -h string:x-dunst-stack-tag:batterynotify "WARNING" "Battery below 20%"

fi

#  BATTERY STATUS DISPLAY ------------------------------------------------------
if [[ "$BAT_STATS" = "Charging" ]]; then
    [ "$BAT_LEVEL" -le 100 ] && BAT_ICON="󱊦"
    [ "$BAT_LEVEL" -le 75  ] && BAT_ICON="󱊥"
    [ "$BAT_LEVEL" -le 50  ] && BAT_ICON="󱊤"
    [ "$BAT_LEVEL" -le 25  ] && BAT_ICON="󰢟"
else
    [ "$BAT_LEVEL" -le 100 ] && BAT_ICON="󱊣"
    [ "$BAT_LEVEL" -le 75  ] && BAT_ICON="󱊢"
    [ "$BAT_LEVEL" -le 50  ] && BAT_ICON="󱊡"
    [ "$BAT_LEVEL" -le 25  ] && BAT_ICON="󱃍"
fi

printf "${BAT_ICON} ${BAT_LEVEL}%%"
