#!/bin/bash
#
# dwminho-sb-monitor
#  A status monitor module for the dwminho-blocks status bar

CPU_LOAD=$(cat /proc/loadavg | awk '{printf " %s", $1}')
CPU_TEMP=$(sensors | awk '/Core 0/ {printf "%s", $3}' | sed "s/\.[0-9]//g")
MEM_AVAL=$(free --si -h | awk '/Mem/ {printf " %s/%s", $3, $2}')
#HDD_AVAL=$(df -h | awk '/\/$/ {printf " %s/%s", $3, $2}')

case $BLOCK_BUTTON in
    1) setsid -f st -c st-floating -g 140x40 -e htop -u $USER ;;
    6) st -e nvim "$0" ;;
esac

printf "$CPU_LOAD ($CPU_TEMP) $MEM_AVAL"
