#!/bin/bash
# ------------------------------------------------------------------------------
# dwminho-sb-internet  (c) Copyright 2025-  Minho <minhotmog@gmail.com>
#  A internet/VPN module for the dwminho-blocks status bar
# ------------------------------------------------------------------------------

#  MOUSE SIGNAL HANDLING -------------------------------------------------------
case $BLOCK_BUTTON in
    1) setsid -f st -c st-floating -g 80x40 -e nmtui ;;
    3) vpntoggle-ctl ;;
    6) st -e nvim "$0" ;;
esac

#  NETWORK STATUS DISPLAY ------------------------------------------------------
[[ "$(nordvpn status | grep 'Connected')" ]] && VPN_ICON=" [VPN]" || VPN_ICON=""

if   [ "$(cat /sys/class/net/w*/operstate 2>/dev/null)" = "up" ]; then NET_ICON=""
elif [ "$(cat /sys/class/net/e*/operstate 2>/dev/null)" = "up" ]; then NET_ICON="󰈀"
else
    NET_ICON="󰪎"
fi 

printf "${VPN_ICON} ${NET_ICON} "
