#!/bin/bash
#
# dwminho-sb-internet
#  A internet/VPN module for the dwminho-blocks status bar

#CLICKING
case $BLOCK_BUTTON in
    1) setsid -f st -c st-floating -g 80x40 -e nmtui ;;
    3) [[ "$(nmcli general status | grep connected)" ]] && nmcli networking off || nmcli networking on ;;
    6) st -e nvim "$0" ;;
esac

### NETWORK STATUS DISPLAY ###
if   [ "$(cat /sys/class/net/w*/operstate 2>/dev/null)" = "up" ]; then NET_ICON=""
elif [ "$(cat /sys/class/net/e*/operstate 2>/dev/null)" = "up" ]; then NET_ICON="󰈀"
else
    NET_ICON="󰪎"
fi 

[[ "$(nordvpn status | grep 'Connected')" ]] && VPN_ICON=" [VPN]" || VPN_ICON=""

printf "${VPN_ICON} ${NET_ICON} "
